version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
  # volumes:
  #   - elastic:/usr/share/elasticsearch/config/certs

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  apm:
    image: docker.elastic.co/apm/apm-server:8.11.4
    container_name: elastic-apm
    ports:
      - "8200:8200"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    volumes:
      - ${PWD}/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro

# volumes:
#   elastic:

networks:
  elastic:
    driver: bridge
